// BBHC Theater - Sample Movie & Series Data
// Following the specified schemas for Movie/Series Card Object and Detailed View

const contentDatabase = [
    // Movies
    {
        id: "movie-001",
        title: "Inception",
        poster_url: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
        year: 2010,
        genre: ["Action", "Sci-Fi", "Thriller"],
        imdb_rating: 8.8,
        description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
        is_series: false,
        imdb_id: "tt1375666",
        cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy", "Marion Cotillard"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-002",
        title: "The Dark Knight",
        poster_url: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        year: 2008,
        genre: ["Action", "Drama", "Thriller"],
        imdb_rating: 9.0,
        description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        is_series: false,
        imdb_id: "tt0468569",
        cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine", "Gary Oldman"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-003",
        title: "Interstellar",
        poster_url: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        year: 2014,
        genre: ["Sci-Fi", "Drama", "Action"],
        imdb_rating: 8.6,
        description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        is_series: false,
        imdb_id: "tt0816692",
        cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-004",
        title: "Parasite",
        poster_url: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
        year: 2019,
        genre: ["Drama", "Thriller", "Comedy"],
        imdb_rating: 8.5,
        description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
        is_series: false,
        imdb_id: "tt6751668",
        cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-005",
        title: "The Shawshank Redemption",
        poster_url: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
        year: 1994,
        genre: ["Drama"],
        imdb_rating: 9.3,
        description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        is_series: false,
        imdb_id: "tt0111161",
        cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-006",
        title: "Pulp Fiction",
        poster_url: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
        year: 1994,
        genre: ["Drama", "Thriller", "Action"],
        imdb_rating: 8.9,
        description: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
        is_series: false,
        imdb_id: "tt0110912",
        cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-007",
        title: "Get Out",
        poster_url: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
        year: 2017,
        genre: ["Horror", "Thriller"],
        imdb_rating: 7.7,
        description: "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.",
        is_series: false,
        imdb_id: "tt5052448",
        cast: ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford", "Catherine Keener"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-008",
        title: "The Grand Budapest Hotel",
        poster_url: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
        year: 2014,
        genre: ["Comedy", "Drama"],
        imdb_rating: 8.1,
        description: "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glorious years under an exceptional concierge.",
        is_series: false,
        imdb_id: "tt2278388",
        cast: ["Ralph Fiennes", "F. Murray Abraham", "Mathieu Amalric", "Adrien Brody"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-009",
        title: "Mad Max: Fury Road",
        poster_url: "https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
        year: 2015,
        genre: ["Action", "Sci-Fi", "Thriller"],
        imdb_rating: 8.1,
        description: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.",
        is_series: false,
        imdb_id: "tt1392190",
        cast: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult", "Hugh Keays-Byrne"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-010",
        title: "Dune",
        poster_url: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
        year: 2021,
        genre: ["Sci-Fi", "Action", "Drama"],
        imdb_rating: 8.0,
        description: "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions of a dark future.",
        is_series: false,
        imdb_id: "tt1160419",
        cast: ["Timothée Chalamet", "Rebecca Ferguson", "Oscar Isaac", "Zendaya"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    
    // Series
    {
        id: "series-001",
        title: "Breaking Bad",
        poster_url: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
        year: 2008,
        genre: ["Drama", "Thriller"],
        imdb_rating: 9.5,
        description: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
        is_series: true,
        imdb_id: "tt0903747",
        cast: ["Bryan Cranston", "Aaron Paul", "Anna Gunn", "Dean Norris"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "series-002",
        title: "Stranger Things",
        poster_url: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
        year: 2016,
        genre: ["Sci-Fi", "Horror", "Drama"],
        imdb_rating: 8.7,
        description: "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.",
        is_series: true,
        imdb_id: "tt4574334",
        cast: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder", "David Harbour"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "series-003",
        title: "The Last of Us",
        poster_url: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
        year: 2023,
        genre: ["Drama", "Sci-Fi", "Thriller"],
        imdb_rating: 8.8,
        description: "Twenty years after modern civilization has been destroyed, Joel must smuggle Ellie out of an oppressive quarantine zone and across the country while facing dangers along the way.",
        is_series: true,
        imdb_id: "tt3581920",
        cast: ["Pedro Pascal", "Bella Ramsey", "Anna Torv", "Gabriel Luna"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "series-004",
        title: "The Crown",
        poster_url: "https://image.tmdb.org/t/p/w500/1M876KPjulVwppEpldhdc8V4o68.jpg",
        year: 2016,
        genre: ["Drama"],
        imdb_rating: 8.6,
        description: "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the 20th century.",
        is_series: true,
        imdb_id: "tt4786824",
        cast: ["Claire Foy", "Olivia Colman", "Imelda Staunton", "Matt Smith"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "series-005",
        title: "Wednesday",
        poster_url: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
        year: 2022,
        genre: ["Comedy", "Horror", "Drama"],
        imdb_rating: 8.1,
        description: "Follows Wednesday Addams' years as a student at Nevermore Academy, where she attempts to master her emerging psychic ability, thwart a killing spree, and solve the mystery that embroiled her parents.",
        is_series: true,
        imdb_id: "tt13443470",
        cast: ["Jenna Ortega", "Catherine Zeta-Jones", "Luis Guzmán", "Gwendoline Christie"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "series-006",
        title: "The Witcher",
        poster_url: "https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg",
        year: 2019,
        genre: ["Action", "Drama", "Sci-Fi"],
        imdb_rating: 8.0,
        description: "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
        is_series: true,
        imdb_id: "tt5180504",
        cast: ["Henry Cavill", "Anya Chalotra", "Freya Allan", "Joey Batey"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-011",
        title: "Oppenheimer",
        poster_url: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
        year: 2023,
        genre: ["Drama", "Thriller"],
        imdb_rating: 8.3,
        description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
        is_series: false,
        imdb_id: "tt15398776",
        cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-012",
        title: "Everything Everywhere All at Once",
        poster_url: "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
        year: 2022,
        genre: ["Action", "Comedy", "Sci-Fi"],
        imdb_rating: 7.8,
        description: "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
        is_series: false,
        imdb_id: "tt6710474",
        cast: ["Michelle Yeoh", "Stephanie Hsu", "Ke Huy Quan", "Jamie Lee Curtis"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-013",
        title: "John Wick",
        poster_url: "https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
        year: 2014,
        genre: ["Action", "Thriller"],
        imdb_rating: 7.4,
        description: "An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and took everything from him.",
        is_series: false,
        imdb_id: "tt2911666",
        cast: ["Keanu Reeves", "Michael Nyqvist", "Alfie Allen", "Willem Dafoe"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-014",
        title: "The Matrix",
        poster_url: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
        year: 1999,
        genre: ["Action", "Sci-Fi"],
        imdb_rating: 8.7,
        description: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
        is_series: false,
        imdb_id: "tt0133093",
        cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-015",
        title: "The Conjuring",
        poster_url: "https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
        year: 2013,
        genre: ["Horror", "Thriller"],
        imdb_rating: 7.5,
        description: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
        is_series: false,
        imdb_id: "tt1457767",
        cast: ["Patrick Wilson", "Vera Farmiga", "Ron Livingston", "Lili Taylor"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "series-007",
        title: "House of the Dragon",
        poster_url: "https://image.tmdb.org/t/p/w500/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
        year: 2022,
        genre: ["Drama", "Action", "Sci-Fi"],
        imdb_rating: 8.4,
        description: "An internal succession war within House Targaryen at the height of its power, 172 years before the birth of Daenerys Targaryen.",
        is_series: true,
        imdb_id: "tt11198330",
        cast: ["Matt Smith", "Emma D'Arcy", "Olivia Cooke", "Rhys Ifans"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "series-008",
        title: "Black Mirror",
        poster_url: "https://image.tmdb.org/t/p/w500/5UaYsGZOFhjFDwQix3L0hyRT9qI.jpg",
        year: 2011,
        genre: ["Sci-Fi", "Thriller", "Drama"],
        imdb_rating: 8.7,
        description: "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.",
        is_series: true,
        imdb_id: "tt2085059",
        cast: ["Jesse Plemons", "Cristin Milioti", "Jimmi Simpson", "Michaela Coel"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-016",
        title: "Spider-Man: Across the Spider-Verse",
        poster_url: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
        year: 2023,
        genre: ["Action", "Comedy", "Sci-Fi"],
        imdb_rating: 8.7,
        description: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
        is_series: false,
        imdb_id: "tt9362722",
        cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac", "Jake Johnson"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-017",
        title: "A Quiet Place",
        poster_url: "https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg",
        year: 2018,
        genre: ["Horror", "Thriller", "Drama"],
        imdb_rating: 7.5,
        description: "In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.",
        is_series: false,
        imdb_id: "tt6644200",
        cast: ["Emily Blunt", "John Krasinski", "Millicent Simmonds", "Noah Jupe"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-018",
        title: "Top Gun: Maverick",
        poster_url: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
        year: 2022,
        genre: ["Action", "Drama"],
        imdb_rating: 8.3,
        description: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it.",
        is_series: false,
        imdb_id: "tt1745960",
        cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly", "Jon Hamm"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-019",
        title: "Barbie",
        poster_url: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
        year: 2023,
        genre: ["Comedy", "Drama"],
        imdb_rating: 6.9,
        description: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
        is_series: false,
        imdb_id: "tt1517268",
        cast: ["Margot Robbie", "Ryan Gosling", "America Ferrera", "Will Ferrell"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    },
    {
        id: "movie-020",
        title: "The Batman",
        poster_url: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
        year: 2022,
        genre: ["Action", "Thriller", "Drama"],
        imdb_rating: 7.8,
        description: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
        is_series: false,
        imdb_id: "tt1877830",
        cast: ["Robert Pattinson", "Zoë Kravitz", "Jeffrey Wright", "Colin Farrell"],
        streaming_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        player_controls: ["Play", "Pause", "Seek", "Fullscreen", "Volume"]
    }
];

// Export for use in other scripts
window.contentDatabase = contentDatabase;
